baseURL = "https://padasch.netlify.app/"
title = "Hi, I'm Pascal 👋"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "with Blogdown and Hugo"
  description = "... and this is where I share my thoughts and ideas!"
  avatarURL = "/images/picture_cv_ps.jpeg"
  avatarSize = "size-m"
  customHeadHTML = "<script>console.log('Any HTML')</script>"
  socialIcons = [
    {name = "github", url = "https://github.com/padasch"},
    {name = "twitter", url = "https://twitter.com/padasch_"},
    {name = "linkedin", url = "https://linkedin.com/schneiderpascal"},
  ]
  metaKeywords = ["blog", "phd", "science", "academia", "earth system", "data science", "biosphere modeling"]
  showPostsOnHomePage = "recent"
  accentColor = "#08F"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
    [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
    
  [[menu.main]]
    name = "Academia"
    url = "/academia/"
    weight = 3

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 4


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
