---
title: "The Beer Afterwards is (probably) More Important Than the Talk Before it"
date: 2022-07-26
description: "In this post I reflect on attending my first scientific conference and share why meeting people is probably more important than listening to talks."
tags: ["science", "conference", "imposter syndrom", "PhD"]
draft: false
type: post
weight: 25
showTableOfContents: true
---

## Too Long, Didn't Read

-   Scientific conferences are for meeting people - use that opportunity!
-   Asking questions as a fresh PhD is intimidating but not a reason to hold back. Try to get into a
    private conversation if you do not feel comfortable asking after a talk.
-   Have a goal in mind of what you want to get out of the conference - are there any people you
    want to talk to about a specific question? Do you want to give a great talk? Do you want to
    strike up new collaborations?

## Introduction

Last week I had the great opportunity to attend my first scientific conference - the [8th edition of
the MMEE](https://research.reading.ac.uk/mmee2022/) conference in Reading, UK. Moreover, I did not
only attend but was offered to give a talk. The only problem was that I knew neither how to attend a
conference nor how to give a proper scientific talk. In this blog post, I will share my insights on
how I had to learn the former whilst the latter is scheduled for another post.

## The Value of The Beer Afterwards

During a conference, there are a lot of new inputs to digest and many people to meet. This can be
very exhausting and you can get lost quickly. So you need a strategy that helps you to get the most
out of it. When you google for general tips and tricks on how to attend a scientific conference,
there is plenty of valuable advice. I have linked some of them at the bottom of this post for
further reading. Personally, I highly recommend the paper by Leiniger et al. (2020), which covers 10
rules, and each is split into the perspective of attending in-person or online and as a PhD or as a
mentor.

The most important message that stuck to me when reading up online - and that was confirmed when
talking to colleagues - is that the beer after the talk is quite often more valuable than the talk
itself. But what does that mean?

First of all, there are various reasons why talks (unfortunately) may not be very useful. People may
not prepare properly for and more or less copy-paste the text of their recent paper onto their
slides. Others may just not be well-versed or have trouble talking to an audience. Others may talk
way too fast to understand them or talk too long so that there is no more time for questions. Other
times you may be distracted because of a new mail or because you are simply drained from the long
day.

For these reasons, it is important that you engage with others outside the formal conference
framework. One-to-one interactions can bear many more fruits as you can deep-dive into a topic and
clarify questions on the go. Even better, doing this during an after-conference coffee or beer
allows for a more creative, informal talk and creates a safe space to explore seemingly silly ideas.
A talk itself may be inspiring and insightful, but that is not guaranteed. Also, you may not feel
confident asking questions in front of a big crowd, or there is no time to do so at all. You,
however, can almost certainly steer a conversation to get the most out of it.

## Be Proactive to Get the Most

But how do you get to talk to others? For an extrovert personality, this may not be difficult and
they just strike up conversations on the go. However, for more introverted people, this can pose a
major barrier. I was lucky enough to have a peer group at the conference that allowed me to get
introduced to other people very quickly. Therefore, I would advise you to arrange with a few people
in advance to not be lost on your own. Then, you can build from this peer group and introduce and
get introduced to new people.

If you cannot or do not want to rise your topic even in a smaller group, try to actively get into
one-to-one situations. Go and grab a coffee at the same time as someone you want to talk to, check
if you are staying in the same hotel so you could meet for breakfast or during the commute, etc. It
is very important and highly rewarding to be proactive here and to make the most out of your time.

## Don't Waste Your Time and Energy

The plethora of talks given at a presentation directly induces a sense of FOMO (Fear Of Missing Out)
which should not be underestimated. And this FOMO can get you running from session to session,
trying to catch up with all the topics whilst quickly draining your batteries. As a well-seasoned
in-lecture sleeper, I learned that attending a talk makes only sense if you are paying attention to
it. Way too many of the people in our sessions were relentlessly working on their mail inbox or
scrolling on their phones. This is not just rude towards the presenter but also highly inefficient,
in my opinion. If you realize you are too tired or too busy, just skip the next talk, finish that
mail or go for a walk. After that, you will be much more ready to benefit from the shared knowledge.

## A Note on the Beloved Imposter Syndrom

As a fresh PhD in a new field, I often struggled to follow a topic or to identify objectively "good"
questions to ask. This feeling of inferiority - what is commonly referred to as imposter syndrome -
held me back from asking questions after a talk more often than I'd like to admit. I did so mainly
to not embarrass myself by asking a (again) objetively "stupid" question - sometimes only to find
others asking similar questions. I think that part of the imposter syndrome is one's own perception
of academia. If you judge others by their questions and reactions (e.g., whether the question was a
good or stupid one in your eyes), you subconsciously start to assume others judge you the same way.
And this only feeds back to you and opens a second-guessing rabbit hole that holds you back.

I must admit that my field may not be the average here, but I always felt very comfortable talking
to others - although I often had to overcome the above-mentioned feelings. What also worked very
well for me was to ask questions in the one-to-one conversations mentioned in the beginning. I was
often surprised to learn that a seemingly silly question had no clear answers and others struggled
similarly to find a good answer.

## Further Resources

To keep this post within a reasonable length, I leave the topic of giving a good talk for another
post. However, here are some quick reads that I can recommend:

-   On attending a conference:
    -   [Leininger E, Shaw K, Moshiri N, et al (2021) Ten simple rules for attending your first
        conference. PLOS Computational Biology
        17:e1009133.](https://doi.org/10.1371/journal.pcbi.1009133) (**highly recommended**)
    -   [A Complete Guide to Academic
        Conferences](https://www.exordo.com/blog/guide-to-academic-conferences/)
    -   [What Are Academic Conferences Good
        For?](https://www.forbes.com/sites/chadorzel/2015/06/17/what-are-academic-conferences-good-for/?sh=7c75c0ed7b66)
    -   [The PhD's Guide to Academic
        Conferences](https://blogs.scientificamerican.com/guest-blog/the-phds-guide-to-academic-conferences/)
-   On giving a talk
    -   [Your conference presentation checklist \| Blog \| Ex
        Ordo](https://www.exordo.com/blog/your-conference-presentation-checklist/)
    -   [Research Methods Chapter 7 - Presenting Your
        Results](https://researchmethods.uni.edu/chapter-7-presenting-your-results)
    -   [11 Tips for Presenting at a
        Conference](https://www.exordo.com/blog/presenting-at-a-conference/)
